home:
    path: /
    controller: App\Controller\DefaultController::indexAction

category:
    path: /category/{id}
    controller: App\Controller\DefaultController::categoryAction

papierpeint:
    path: /papierpeint
    controller: App\Controller\DefaultController::papierpeintAction

collectionbase:
    path: /collectionbase
    controller: App\Controller\DefaultController::collectionbaseAction

collectionpersonnaliser:
    path: /collectionpersonnaliser
    controller: App\Controller\DefaultController::collectionpersonnaliserAction

about:
    path: /about
    controller: App\Controller\DefaultController::aboutAction

portfolio:
    path: /portfolio
    controller: App\Controller\DefaultController::portfolioAction

contact:
    path: /contact
    controller: App\Controller\DefaultController::contactAction

register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

collection:
    path: /collection/{id}
    controller: App\Controller\DefaultController::collectionAction

admin:
    path: /admin
    controller: App\Controller\AdminController::homeAction

adminSlider:
    path: /admin/slider/{id}
    controller: App\Controller\AdminController::sliderAction

collBaseCategorys:
    path: /admin/collBaseCategorys/{id}
    controller: App\Controller\AdminController::collBaseCategorysAction

typePapier:
    path: /admin/typePapier/{id}
    controller: App\Controller\AdminController::typePapierAction

delete:
    path: /admin/delete/{repository}/{id}/{redirect}
    controller: App\Controller\AdminController::delete

allUsers:
    path: /admin/allUsers/{id}
    controller: App\Controller\AdminController::allUsersAction

collBaseAdmin:
    path: /admin/collBaseAdmin/{id}
    controller: App\Controller\AdminController::collBaseAdminAction

collBaseImage:
    path: /admin/collBaseImage/{id}/{coll}
    controller: App\Controller\AdminController::collBaseImageAction

basket:
    path: /basket
    controller: App\Controller\UserController::basketAction

paymentOk:
    path: /paymentok/{id}
    controller: App\Controller\UserController::stripeAction

deleteOrder:
    path: /deleteOrder/{id}
    controller: App\Controller\UserController::deleteOrder

myhistory:
    path: /myhistory
    controller: App\Controller\ProfileController::myHistoryAction

editorder:
    path: /editorder/{id}
    controller: App\Controller\ProfileController::editorderAction

updateinfo:
    path: /updateinfo
    controller: App\Controller\ProfileController::updateinfoAction

facture:
    path: /facture/{id}
    controller: App\Controller\ProfileController::factureAction

updateShipping:
    path: /updateShipping/{id}
    controller: App\Controller\UserController::updateShipping